name: Build and release

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Pre_Release: ${{ contains(github.ref, 'dev') }}
      Solution_Name: MKVStudio.sln
      Project_Name: MKVStudio/MKVStudio.csproj
      # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

# Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

# Restore NuGet
      - name: Restore NuGet with dotnet
        run: dotnet restore $env:Solution_Name
      
# Execute all unit tests in the solution    
      - name: Tests
        run: dotnet test $env:Solution_Name

# Build
      - name: Build
        run: dotnet build $env:Project_Name
